spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/bkument_db
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          ai-service:
            connect-timeout: 60000
            read-timeout: 1200000
  neo4j:
    uri: bolt://${DB_HOST}:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

gateway:
  base-url: http://${PUBLIC_IP}:8888
  api-prefix: /api/v1

swagger:
  gateway-url: http://${PUBLIC_IP}:8888/api/v1/social
  host-url: http://${PUBLIC_IP}:8089/social

app:
  services:
    profile: http://profile-service:8081/profile
    document: http://document-service:8086/document
    blog: http://blog-service:8085/blog
    lms: http://lms-service:8082/lms
    email: http://email-service:8084/email