server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    driverClassName: "org.h2.Driver"
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  signerKey: "5016f0096d30f88524edc817d00b36406e26788c87ea9c97d57c4b7758b5f033"
  valid-duration: 3600           #seconds -> 1 hour
  refreshable-duration: 86400   #seconds -> 1 day

swagger:
  host-url: http://localhost:8080/identity

app:
  services:
    profile: http://localhost:8081/profile
