server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/bkument_db"
    driverClassName: "org.postgresql.Driver"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

logging:
  level:
    org.hibernate.orm.connections.pooling: DEBUG
    com.zaxxer.hikari: INFO

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:3600}              #seconds -> 1 hour
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:86400} #seconds -> 1 day

swagger:
  host-url: http://localhost:8080/identity
  gateway-url: ${BACKEND_HOST}/api/v1/identity

app:
  services:
    profile: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}
  base-url: ${APP_BASE_URL:http://localhost:8888}
  fe-url: ${APP_FE_URL:http://localhost:3000}
  internal-api:
    secret: ${INTERNAL_API_SECRET} # generated, ≥ 32 random bytes, rotated periodically

init:
  admin:
    username: ${INIT_ADMIN_USERNAME}
    password: ${INIT_ADMIN_PASSWORD}