spring:
  kafka:
    bootstrap-servers: kafka:9092

  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/bkument_db"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

app:
  services:
    profile: http://profile-service:8081/profile
    lms: http://lms-service:8082/lms

swagger:
<<<<<<< Updated upstream
  host-url: ${BACKEND_HOST}/identity
=======
  gateway-url: ${BACKEND_HOST}/api/v1/identity
>>>>>>> Stashed changes
