server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRESQL:localhost}:5432/bkument_db"
    driverClassName: "org.postgresql.Driver"
    username: ${POSTGRES_USERNAME:username}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.hibernate.orm.connections.pooling: DEBUG
    com.zaxxer.hikari: INFO

jwt:
  signerKey: "5016f0096d30f88524edc817d00b36406e26788c87ea9c97d57c4b7758b5f033"
  valid-duration: 3600           #seconds -> 1 hour
  refreshable-duration: 86400   #seconds -> 1 day

swagger:
  host-url: http://localhost:8080/identity

app:
  services:
    profile: http://localhost:8081/profile
    lms: http://localhost:8082/lms

  init:
    admin:
      username: "admin"
      password: "admin"