version: '3.8'

networks:
  bkument-net:
    driver: bridge

services:
  # ==========================================
  # KAFKA
  # ==========================================
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
    networks:
      - bkument-net
    restart: unless-stopped

  # ==========================================
  # API GATEWAY
  # ==========================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - PUBLIC_IP=${PUBLIC_IP} # Lấy từ file .env
      - BACKEND_HOST=${BACKEND_HOST}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - identity-service
      - profile-service
      - lms-service
      - communication-service

  # ==========================================
  # MICROSERVICES
  # ==========================================
  identity-service:
    build: ./identity-service
    container_name: identity-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
    env_file:
      - .env
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  profile-service:
    build: ./profile-service
    container_name: profile-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
    env_file:
      - .env
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  lms-service:
    build: ./lms-service
    container_name: lms-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
    env_file:
      - .env
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  communication-service:
    build: ./communication-service
    ports:
      - "8099:8099"
    container_name: communication-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SSH_HOST=${SSH_HOST}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
    env_file:
      - .env
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  email-service:
    build: ./email-service
    container_name: email-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - BREVO_URL=${BREVO_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}
    env_file:
      - .env
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  resource-service:
    build: ./resource-service
    container_name: resource-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  blog-service:
    build: ./blog-service
    container_name: blog-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - BACKEND_HOST=${BACKEND_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  document-service:
    build: ./document-service
    container_name: document-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - BACKEND_HOST=${BACKEND_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka
  ai-service:
    build: ./ai-service
    container_name: ai-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - UNSTRUCTURED_API_URL=${UNSTRUCTURED_API_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka

  social-service:
    build: ./social-service
    container_name: social-service
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DB_HOST=${DB_HOST}
      - PUBLIC_IP=${PUBLIC_IP}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - bkument-net
    restart: unless-stopped
    depends_on:
      - kafka
