server:
  port: ${GATEWAY_PORT:8888}

app:
  api-prefix: ${API_PREFIX:/api/v1}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${IDENTITY_SERVICE_URL:https://bkment-identity-service-latest.onrender.com}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: resource_service
          uri: ${RESOURCE_SERVICE_URL:https://bkment-resource-service-latest.onrender.com}
          predicates:
            - Path=${app.api-prefix}/resource/**
          filters:
            - StripPrefix=2

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}
            allowedMethods: ${CORS_ALLOWED_METHODS:*}
            allowedHeaders: ${CORS_ALLOWED_HEADERS:*}
