server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=2
            - id: resource_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/resource/**
              filters:
                - StripPrefix=2
            - id: blog_service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/blog/**
              filters:
                - StripPrefix=2
            - id: document_service
              uri: http://localhost:8086
              predicates:
                - Path=${app.api-prefix}/document/**
              filters:
                - StripPrefix=2
            - id: ai_service
              uri: http://localhost:8087
              predicates:
                - Path=${app.api-prefix}/ai/**
              filters:
                - StripPrefix=2

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:3000
              - https://bkument-fe.vercel.app/
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
