server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: https://spring-boot-app-latest-lv2o.onrender.com
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"