package vn.edu.hcmut.social.enums;

public enum ReportReason {
    DIRECT_QUOTE_NO_CITATION,
    SELF_PLAGIARISM,
    IDEA_PLAGIARISM,
    STRUCTURE_PLAGIARISM,
    PARAPHRASED_NO_CITATION,
    POOR_PARAPHRASING,
    INCOMPLETE_CITATION,
    FALSIFIED_SOURCE,
    MISSING_REFERENCES,
    OTHERS
}
