spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST}:27017/communication?authSource=admin

  kafka:
    bootstrap-servers: kafka:9092

ssh:
  tunnel:
    enabled: false

app:
  internal-api:
    secret: ${INTERNAL_API_SECRET}
  services:
    identity:
      url: http://identity-service:8080/identity
    profile:
      url: http://profile-service:8081/profile
    lms:
      url: http://lms-service:8082/lms

swagger:
  gateway-url: ${BACKEND_HOST}/api/v1/communication
