
spring:
  application:
    name: communication-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST:127.0.0.1}:27017/communication?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: communication-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: vn.edu.hcmut.communication.notification.event.EnrollmentNotificationEvent
        spring.json.trusted.packages: "*"
ssh:
  tunnel:
    enabled: false
    host: ${SSH_HOST:localhost}
    port: 22
    user: ${SSH_USERNAME:username}
    password: ${SSH_PASSWORD:username}
    local-port: 27018
    remote-port: 27017

server:
  port: 8083
  servlet:
    context-path: /communication

app:
  services:
    identity:
      url: http://localhost:8080/identity
    profile:
      url: http://localhost:8081/profile
    lms:
      url: http://localhost:8082/lms

swagger:
  host-url: http://localhost:8083/communication
  gateway-url: http://localhost:8888/api/v1/communication
