--
-- PostgreSQL database dump
--

\restrict 5KPthB6owcTV4r4BNBTfs2D3IUg0PYI5S9h38xqpEj1TrYqj4kAckhrzkP9Tc4P

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: bkument
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO bkument;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: bkument
--

COMMENT ON SCHEMA public IS '';


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: bkument
--

CREATE TYPE public.user_role AS ENUM (
    'STUDENT',
    'TUTOR',
    'MODERATOR',
    'ADMIN'
);


ALTER TYPE public.user_role OWNER TO bkument;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.account (
    id character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255)
);


ALTER TABLE public.account OWNER TO bkument;

--
-- Name: account_roles; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.account_roles (
    account_id character varying(255) NOT NULL,
    role character varying(255)
);


ALTER TABLE public.account_roles OWNER TO bkument;

--
-- Name: blog_asset; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.blog_asset (
    id character varying(255) NOT NULL,
    resource_id character varying(255) NOT NULL
);


ALTER TABLE public.blog_asset OWNER TO bkument;

--
-- Name: class_room; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.class_room (
    id character varying(255) NOT NULL,
    description character varying(255),
    end_date date,
    name character varying(255),
    schedule character varying(255),
    start_date date,
    status character varying(255),
    topic_id character varying(255),
    tutor_id character varying(255) NOT NULL,
    CONSTRAINT class_room_status_check CHECK (((status)::text = ANY ((ARRAY['ENROLLING'::character varying, 'ONGOING'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.class_room OWNER TO bkument;

--
-- Name: class_schedules; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.class_schedules (
    id bigint NOT NULL,
    day_of_week character varying(255),
    end_time time(6) without time zone,
    start_time time(6) without time zone,
    class_id character varying(255),
    CONSTRAINT class_schedules_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


ALTER TABLE public.class_schedules OWNER TO bkument;

--
-- Name: class_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: bkument
--

ALTER TABLE public.class_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.document (
    asset_id character varying(255),
    description text,
    document_type character varying(255),
    download_count integer,
    is_downloadable boolean,
    summary text,
    id character varying(255) NOT NULL,
    course text,
    university text
);


ALTER TABLE public.document OWNER TO bkument;

--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.enrollments (
    id character varying(255) NOT NULL,
    enrolled_at timestamp(6) without time zone,
    status smallint,
    user_id character varying(255),
    class_id character varying(255),
    CONSTRAINT enrollments_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.enrollments OWNER TO bkument;

--
-- Name: invalidated_token; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.invalidated_token (
    id character varying(255) NOT NULL,
    expiry_time timestamp(6) without time zone
);


ALTER TABLE public.invalidated_token OWNER TO bkument;

--
-- Name: post; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.post (
    content text NOT NULL,
    id character varying(255) NOT NULL,
    cover_image character varying(255) NOT NULL
);


ALTER TABLE public.post OWNER TO bkument;

--
-- Name: resource; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.resource (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    owner_id character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    updated_at timestamp(6) without time zone,
    visibility character varying(255) NOT NULL
);


ALTER TABLE public.resource OWNER TO bkument;

--
-- Name: subject; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.subject (
    id character varying(50) NOT NULL,
    name character varying(255)
);


ALTER TABLE public.subject OWNER TO bkument;

--
-- Name: topic; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.topic (
    id character varying(255) NOT NULL,
    name character varying(255),
    subject_id character varying(50)
);


ALTER TABLE public.topic OWNER TO bkument;

--
-- Name: tutor; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.tutor (
    id character varying(255) NOT NULL,
    average_rating double precision,
    introduction character varying(255),
    rating_count integer,
    status character varying(255),
    avatar character varying(255),
    name character varying(255)
);


ALTER TABLE public.tutor OWNER TO bkument;

--
-- Name: tutor_subjects; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.tutor_subjects (
    tutor_id character varying(255) NOT NULL,
    subject_id character varying(255)
);


ALTER TABLE public.tutor_subjects OWNER TO bkument;

--
-- Name: universities; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.universities (
    id integer NOT NULL,
    abbreviation character varying(255) NOT NULL,
    logo_url character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.universities OWNER TO bkument;

--
-- Name: universities_id_seq; Type: SEQUENCE; Schema: public; Owner: bkument
--

ALTER TABLE public.universities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.universities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: bkument
--

CREATE TABLE public.user_profiles (
    id character varying(255) NOT NULL,
    account_id character varying(255) NOT NULL,
    address character varying(255),
    avatar_url character varying(255),
    bio text,
    dob date,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255),
    points bigint,
    university_id integer
);


ALTER TABLE public.user_profiles OWNER TO bkument;

--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.account (id, username, password, role) FROM stdin;
f249e50a-86f8-4220-8260-7bdb0f701ecb	admin	$2a$10$NBYjyBJsQSooOC3A0ES6d.ly.Jxdo84NXm7TRzpEPXDFGld9JW7jy	ADMIN
3d6b47e6-c5fb-4815-9645-0da89d00e82c	quanglee	$2a$10$0cEdTOcHpsIXZy/kZdhT2.1ML2fqQ/sDWQ21.PLvE06lN90rlS6gq	USER
47315afa-ddc5-436d-a543-545aadc50e97	quangrr	$2a$10$jOm.ai0Vkq9CxvEsRZghqey.m71kkqWo9gIbNZhb42dYC0s5SLKAa	USER
a1ba5803-d13e-4b0d-8cb7-c50cb6926772	string	$2a$10$56E29WrAzHgeYV.6ycIROOqIVlISkfZLzfRptGRb0n7E57mNpGUaO	USER
4503da70-5f3c-4e23-9a02-0d8f21c6dde3	baotien	$2a$10$j/G/Di6jGmeBzgZQhMbiZOGGzBb6uuORzFp78fcO6NzWyoqAYlgGK	USER
5c240a33-aa0c-4d98-bd88-68c52dc86486	phamlong	$2a$10$aHyn.lEHnY4reObYmzVOCuWcqM6FJy08QAln4QRNEMvGPelCIPrr2	USER
20ca4bf1-97e2-45b7-b35b-4b29914ec589	phamtien	$2a$10$CJ8TmbuqdVdtCcAwT3Z.NOqY8Btzsv4aMIC4rONqOXCigE/1EEx9y	USER
47315afa-ddc5-436d-a543-545abdc50e97	khoale	$2a$10$aHyn.lEHnY4reObYmzVOCuWcqM6FJy08QAln4QRNEMvGPelCIPrr2	USER
fd87318b-a289-4b85-91fd-e8ce29c708fd	minh.nguyen	$2a$10$CmdghPMp2Wquq2wpPV9bYucAQeDB2FtXobZB4fqrjFnhPqjNJe3Eq	USER
0371f5a5-2b7c-4d0d-9c2e-64b999b8274b	ly.quang123	$2a$10$sXRiRNHValqFHmw0MRJkAeM75x7gRaJjyz1qfjagNi11A59t/OC8y	\N
\.


--
-- Data for Name: account_roles; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.account_roles (account_id, role) FROM stdin;
f249e50a-86f8-4220-8260-7bdb0f701ecb	ADMIN
3d6b47e6-c5fb-4815-9645-0da89d00e82c	USER
47315afa-ddc5-436d-a543-545aadc50e97	USER
a1ba5803-d13e-4b0d-8cb7-c50cb6926772	USER
4503da70-5f3c-4e23-9a02-0d8f21c6dde3	USER
5c240a33-aa0c-4d98-bd88-68c52dc86486	USER
20ca4bf1-97e2-45b7-b35b-4b29914ec589	USER
47315afa-ddc5-436d-a543-545abdc50e97	USER
fd87318b-a289-4b85-91fd-e8ce29c708fd	USER
fd87318b-a289-4b85-91fd-e8ce29c708fd	TUTOR
0371f5a5-2b7c-4d0d-9c2e-64b999b8274b	USER
\.


--
-- Data for Name: blog_asset; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.blog_asset (id, resource_id) FROM stdin;
a	ab3ef374-dcda-4299-9f5e-68f5702a8cf7
ab	ab3ef374-dcda-4299-9f5e-68f5702a8cf7
abc	ab3ef374-dcda-4299-9f5e-68f5702a8cf7
abcd	ab3ef374-dcda-4299-9f5e-68f5702a8cf7
abcde	ab3ef374-dcda-4299-9f5e-68f5702a8cf7
http://localhost:8888/api/v1/resource/download/asset/78913a6b-b646-4fd2-93e1-a07c13bb6923.webp	b4eb7322-e7a8-46aa-bcff-307896a665c0
http://localhost:8888/api/v1/resource/download/asset/217d3ff1-50a6-44e8-8485-f372542016a8.png	b4eb7322-e7a8-46aa-bcff-307896a665c0
http://localhost:8888/api/v1/resource/download/asset/68cbaaf7-24f1-4d8d-9511-149b283bcff7.webp	f4891a29-007e-4242-b26e-76dcf2a3294c
http://localhost:8888/api/v1/resource/download/asset/62d96cea-0765-4ca5-98bb-a269676069c3.png	f4891a29-007e-4242-b26e-76dcf2a3294c
http://localhost:8888/api/v1/resource/download/asset/46dd89cb-92b1-421e-a5f9-8d37068cc389.webp	8cfbf39f-07b2-4eed-9464-62ab33054749
http://localhost:8888/api/v1/resource/download/asset/ee26c7c1-e71b-4bff-8532-57a4f518e3a0.png	8cfbf39f-07b2-4eed-9464-62ab33054749
http://localhost:8888/api/v1/resource/download/asset/cc7bcdc2-c752-41a3-9a1f-4b3b3d25ba95.webp	684ef412-6f7f-43f5-a0a9-5739cf8b4013
http://localhost:8888/api/v1/resource/download/asset/7daeb47a-8470-4e75-b2d6-2690f11d393b.webp	684ef412-6f7f-43f5-a0a9-5739cf8b4013
http://localhost:8888/api/v1/resource/download/asset/e1c47fcc-fe14-4cd6-8c2e-bef63585faf9.webp	684ef412-6f7f-43f5-a0a9-5739cf8b4013
http://localhost:8888/api/v1/resource/download/asset/2933a814-6b3c-439b-9d1e-83ff1fc49ccb.webp	684ef412-6f7f-43f5-a0a9-5739cf8b4013
http://localhost:8888/api/v1/resource/download/asset/75518b81-cada-45e4-a22a-bba87e5201e7.png	4817032e-309f-4a0b-af0b-3e2da3d985da
http://localhost:8888/api/v1/resource/download/asset/40eecaaf-5d4e-4bb9-bd71-709e7275313e.png	4817032e-309f-4a0b-af0b-3e2da3d985da
http://localhost:8888/api/v1/resource/download/asset/80732539-8838-4187-a780-0b636d67e039.webp	772f3db7-64fb-4d42-826b-d90a29013116
http://localhost:8888/api/v1/resource/download/asset/ca88ad23-0917-45c8-a9b3-68eecd974d39.webp	772f3db7-64fb-4d42-826b-d90a29013116
\.


--
-- Data for Name: class_room; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.class_room (id, description, end_date, name, schedule, start_date, status, topic_id, tutor_id) FROM stdin;
7879ecfd-ada0-47c9-97b1-5e3bd84c4847	Thực hành ngăn chặn 10 lỗ hổng bảo mật hàng đầu theo tiêu chuẩn OWASP	2026-05-15	Bảo mật Web chuyên sâu 2026	\N	2026-02-15	ENROLLING	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
5f352d26-7c24-45c5-9c91-92ab45140bdc	Hướng dẫn phân tích yêu cầu và xây dựng Mô hình thực thể kết hợp (ERD) chuẩn xác cho các hệ thống phần mềm lớn.	2026-03-01	Thiết kế CSDL với ERD	\N	2026-02-01	ENROLLING	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
3862d72d-34a3-4612-94ff-f1a452652217	Thực hành ngăn chặn 10 lỗ hổng bảo mật hàng đầu theo tiêu chuẩn OWASP.	2026-05-15	Bảo mật Web chuyên sâu 2026	\N	2026-02-15	ENROLLING	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
f6e7b6fc-132d-4e0b-89b7-460979195c74	Lập trình nâng cao	2026-02-26	Lập trình nâng cao	\N	2026-02-05	ENROLLING	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
c7257c8f-5f98-4e2a-a498-3307c99a8b9b	Lớp thực hành vẽ Mapping từ ERD	2026-04-21	Lớp thực hành vẽ Mapping từ ERD	\N	2026-03-16	CANCELLED	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
d0793e4e-9b66-45f5-995c-ea7e0e743ae8	Ứng dụng CNTT trong Hóa học	2026-03-01	Ứng dụng CNTT trong Hóa học	\N	2026-02-08	CANCELLED	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
6fd74fb0-ad0c-4fc1-acac-4b21c93a9c0c	Thương mại điện tử	2026-02-28	Thương mại điện tử	\N	2026-02-07	CANCELLED	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
491ee8b3-c46d-4525-9697-5171ed45405e	Introduction to AI	2026-03-21	Introduction to AI	\N	2026-03-07	CANCELLED	cc929469-37f0-4f03-ba1f-3c375baf80d2	95da25ef-99da-4a8f-86a2-2ec0d400f307
a367a66e-744c-469e-890d-7dddf481b6df	Nhập môn Trí tuệ Nhân tạo	2026-02-27	Nhập môn Trí tuệ Nhân tạo	\N	2026-02-06	CANCELLED	3c46a94f-d8ae-4606-a380-9574b7cec880	95da25ef-99da-4a8f-86a2-2ec0d400f307
\.


--
-- Data for Name: class_schedules; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.class_schedules (id, day_of_week, end_time, start_time, class_id) FROM stdin;
7	MONDAY	20:00:00	18:00:00	7879ecfd-ada0-47c9-97b1-5e3bd84c4847
8	WEDNESDAY	20:00:00	18:00:00	7879ecfd-ada0-47c9-97b1-5e3bd84c4847
9	TUESDAY	21:00:00	19:00:00	5f352d26-7c24-45c5-9c91-92ab45140bdc
10	THURSDAY	21:00:00	19:00:00	5f352d26-7c24-45c5-9c91-92ab45140bdc
11	SUNDAY	20:00:00	18:00:00	3862d72d-34a3-4612-94ff-f1a452652217
12	SATURDAY	20:00:00	18:00:00	3862d72d-34a3-4612-94ff-f1a452652217
13	MONDAY	12:55:00	22:55:00	f6e7b6fc-132d-4e0b-89b7-460979195c74
14	WEDNESDAY	15:10:00	13:10:00	a367a66e-744c-469e-890d-7dddf481b6df
15	SUNDAY	15:10:00	13:10:00	a367a66e-744c-469e-890d-7dddf481b6df
16	MONDAY	12:34:00	19:34:00	6fd74fb0-ad0c-4fc1-acac-4b21c93a9c0c
17	THURSDAY	16:02:00	15:02:00	d0793e4e-9b66-45f5-995c-ea7e0e743ae8
18	FRIDAY	18:27:00	17:27:00	c7257c8f-5f98-4e2a-a498-3307c99a8b9b
19	FRIDAY	22:29:00	20:29:00	491ee8b3-c46d-4525-9697-5171ed45405e
\.


--
-- Data for Name: document; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.document (asset_id, description, document_type, download_count, is_downloadable, summary, id, course, university) FROM stdin;
d1dd0ca8-e8ac-487c-95f6-fd19b988fb44.pdf	123	\N	0	t	\N	86b83329-ac18-426f-907d-25491aac2d6f	\N	\N
4f687547-7050-451d-b640-31e0a92532be.pdf	de cuoi ky	\N	0	t	\N	a0a36ef5-aac7-4ec9-8ae1-d31bed2e5c81	\N	\N
1be06c2f-f81e-4ebe-b820-fd594d663edc.pdf	hehe	\N	0	t	\N	da895b67-9fb3-4ca3-8235-6396cb775c2a	\N	\N
9bdd078e-5d41-4a49-95a4-6267b97e8718.pdf	123	\N	0	t	\N	acfab06b-a474-473f-b25a-a7742fde5a45	\N	\N
57573d93-9db9-4477-a30d-6d143a7fe33f.pdf	123	\N	0	t	\N	09d3734c-5847-451b-8475-1f885a144236	\N	\N
b8af183a-b7db-44ce-bb44-8ca50fcbc949.pdf	an element of a sentence that is required by syntactic constraints but carries little or no semantic information, for example the word it as a subject in it is a pity that she left, where the true subject is that she left.\n	application/pdf	54	t	\N	9f30a3ce-a937-42ca-a3e5-faff19931f09		Bachs khooooo
f1994104-a3e7-45d0-8640-76f7d910449a.docx	an element of a sentence that is required by syntactic constraints but carries little or no semantic information, for example the word it as a subject in it is a pity that she left, where the true subject is that she left.\n	application/vnd.openxmlformats-officedocument.wordprocessingml.document	17	t	\N	a6a32582-f025-4091-9675-6ad8f774dbf6	Heeeeee	Bachs khooooo
c3909bb3-6f5f-4283-a45e-11c309848812.docx	Bài thi tiếng anh	\N	22	t	\N	e58907a3-e4f3-486f-ade8-4901f7d2d3c4	Hehe	Bachs khoa U
b348952d-7ee5-4a56-ade3-7b36ee6a13a7.pdf	Đây là file báo cáo đồ án	application/pdf	2	t	\N	918a6ca4-b957-48eb-8b62-189b873c315b	Đồ án	Bách khoa University
a2fee27c-74c6-4c5b-9bd3-3311beb4ed4f.png	123	\N	33	t	\N	a0a9b085-6641-4fc4-84cc-229648876353	\N	\N
587229a2-6599-4b1e-b37c-f1080253125d.docx	asdasdas	application/vnd.openxmlformats-officedocument.wordprocessingml.document	19	t	\N	42fba902-d39c-4817-85b6-5b5bfb2f67c1	dasdasdasd	asd
baa5226e-a1df-434a-875a-92c5fa65fb99.pdf	Đây là đề thi lập trình WEB HK202	\N	12	t	\N	a2bf5e9b-1813-4b6b-b060-75312924b37b	\N	\N
\N	DDaya laf description	application/vnd.openxmlformats-officedocument.wordprocessingml.document	0	t	\N	5f0d2f31-238e-4f05-9b56-257643db9a40	hahahaha	HCMUT
bc1212c3-761b-4964-92e3-19a40c226ad2.docx	đây là đề thi	\N	18	t	\N	6d98052c-4f94-48b7-929f-f75a52750be1	\N	\N
e296eb5c-243d-4b7f-a94b-feca7674706b.pdf	Bài vẽ môn Lập trình web	\N	83	f	\N	02ef68d6-fa93-4ffa-9ad5-53ef3d11b804	Hehe	Bachs khoa U
466e6e51-25a0-45c6-9ec1-98d72bb703bb.docx	ádasdasd	application/vnd.openxmlformats-officedocument.wordprocessingml.document	7	t	\N	de7efa45-be6a-423f-a08f-201433010899	ádasdasd	áhcajscbjac
71d4bed5-1c1e-4fea-834c-d41fbfa99fba.pdf	mmmmmmmmmmmmm	application/pdf	22	t	\N	46121fd6-3130-4989-8c7c-934b7313963c	mmmmmmmmmmmmm	mmmmmmmmmmmmm
dd5f148f-da4f-4518-aa07-51124f07b9b4.png	ai z	\N	28	t	\N	e560b01a-50d5-468b-b161-42016d0a16c2	\N	\N
67d63a24-5d08-4db8-aefc-f2f0ac99c14a.pdf	ĐỒ ÁN NEFFFFFF	application/pdf	11	t	\N	7bdfea25-7af5-4546-8cef-1747f8f6c30c	ĐỒ ÁN	HCMUT
852db65f-4090-4e3b-b0c2-0998b3eead48.docx		\N	15	t	\N	094b687d-f40c-40d5-bb88-d569f89d64ae	\N	\N
2df01450-7c22-490c-9203-fa4ad7eab499.docx	123123123	application/vnd.openxmlformats-officedocument.wordprocessingml.document	25	t	\N	20f6eb69-7e3b-451a-8f46-9d6f0bcd241b	HEHE	BÁCH KHOA
762c495c-5779-45dd-bfd7-1116cb41ee39.pdf	Hehe	application/pdf	10	t	\N	44238dd8-94e8-4644-8790-a2ed37e70703	Công nghệ khôgn dệt	Bách khoaaaa
\.


--
-- Data for Name: enrollments; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.enrollments (id, enrolled_at, status, user_id, class_id) FROM stdin;
\.


--
-- Data for Name: invalidated_token; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.invalidated_token (id, expiry_time) FROM stdin;
8d8b4a9b-5db4-4751-a998-2f61ff645c83	2025-11-22 23:08:43
3c6f34eb-0169-4128-abd8-37cd6542990d	2025-11-22 23:12:38
320ae7ef-991c-4356-b96e-8137d1b54877	2025-12-24 04:18:45
bce111c9-38fa-462b-97fa-0a9d6002952a	2025-12-25 15:46:36
ba9df138-2c5f-4cb9-be93-4ee45b2c1236	2025-12-25 16:54:56
2dbb04f1-ad52-48b9-8f89-c9407f6b0d5a	2025-12-25 17:31:10
602a99a6-ea7d-4271-897c-4dcc1e660f72	2025-12-26 08:34:22
c9bbb58a-ccab-499b-a958-4cfebad96b4f	2025-12-29 14:53:59
e1f3f418-a9b0-43ae-b94d-6f8f7500512d	2025-12-29 14:54:29
8568e395-cb4b-499c-829c-5cf873d3dc77	2026-02-06 16:29:20
1e2a58f5-2114-4131-a227-caddb25d666e	2026-02-06 17:19:28
a0a0601f-4116-429b-8b84-11de402d663b	2026-02-06 22:56:31
9fb913cd-8d4c-4b77-9051-f85c328691a1	2026-02-07 18:01:35
c5a828cb-7b86-461f-95e9-74543f674328	2026-02-07 18:12:06
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.post (content, id, cover_image) FROM stdin;
<h2> cần chiến thắng chính mình.&nbsp;</p>	391c7875-f335-40d6-b4b4-4275c096e1d2	https://images2.thanhnien.vn/528068263637045248/2025/12/26/cang-hang-khong-quoc-te-phu-quoc-nha-ga-t2-1766733981877227298326.jpg
<h2> cần chiến thắng chính mình.&nbsp;</p>	fad67e09-0bf8-44cb-bf77-d75a4e6c7df4	https://images2.thanhnien.vn/528068263637045248/2025/12/26/cang-hang-khong-quoc-te-phu-quoc-nha-ga-t2-1766733981877227298326.jpg
<h2> cần chiến thắng chính mình.&nbsp;</p>	97d43ee0-f6b5-4210-bbb9-5a69eb273295	https://images2.thanhnien.vn/528068263637045248/2025/12/26/cang-hang-khong-quoc-te-phu-quoc-nha-ga-t2-1766733981877227298326.jpg
<h2> cần chiến thắng chính mình.&nbsp;</p>	ab3ef374-dcda-4299-9f5e-68f5702a8cf7	https://images2.thanhnien.vn/528068263637045248/2025/12/26/cang-hang-khong-quoc-te-phu-quoc-nha-ga-t2-1766733981877227298326.jpg
<p><img src="http://localhost:8888/api/v1/resource/download/asset/217d3ff1-50a6-44e8-8485-f372542016a8.png"></p><p>hehe</p>	2154aca8-3692-451c-a9ef-318fd9d0ec17	http://localhost:8888/api/v1/resource/download/asset/78913a6b-b646-4fd2-93e1-a07c13bb6923.webp
<p><img src="http://localhost:8888/api/v1/resource/download/asset/217d3ff1-50a6-44e8-8485-f372542016a8.png"></p><p>hehe</p>	b4eb7322-e7a8-46aa-bcff-307896a665c0	http://localhost:8888/api/v1/resource/download/asset/78913a6b-b646-4fd2-93e1-a07c13bb6923.webp
<p><span style="font-family: serif;">ahehaehae</span></p><p><span style="font-family: serif;"><img src="http://localhost:8888/api/v1/resource/download/asset/62d96cea-0765-4ca5-98bb-a269676069c3.png"></span></p>	f4891a29-007e-4242-b26e-76dcf2a3294c	http://localhost:8888/api/v1/resource/download/asset/68cbaaf7-24f1-4d8d-9511-149b283bcff7.webp
<p>hehe</p><p><img src="http://localhost:8888/api/v1/resource/download/asset/ee26c7c1-e71b-4bff-8532-57a4f518e3a0.png"></p>	8cfbf39f-07b2-4eed-9464-62ab33054749	http://localhost:8888/api/v1/resource/download/asset/46dd89cb-92b1-421e-a5f9-8d37068cc389.webp
<h2 style="text-align: justify;"><strong>Khi TP.HCM, Hà Nội và Cục CSGT ứng dụng camera AI để phát hiện vi phạm giao thông, gửi thông báo phạt nguội, không ít ý kiến băn khoăn liệu camera AI có đủ cơ sở pháp lý để xử phạt?</strong></h2><h2 style="text-align: justify;"><strong>CAMERA AI PHẠT THẾ NÀO?</strong></h2><p style="text-align: justify;">Điều 67 luật Trật tự, an toàn giao thông đường bộ (ATGTĐB) 2024 quy định biện pháp phát hiện vi phạm pháp luật về trật tự, ATGTĐB cho phép phát hiện qua hệ thống giám sát bảo đảm an ninh, trật tự, ATGTĐB; hệ thống camera trên tuyến giao thông, trong đô thị.</p><p style="text-align: justify;">Cạnh đó, Thông tư 73/2024 của Bộ Công an cũng quy định, CSGT được kiểm soát thông qua hệ thống, phương tiện, thiết bị, cơ sở dữ liệu về trật tự, ATGTĐB; hệ thống camera trên tuyến giao thông trong đô thị.</p><p style="text-align: justify;">Tính đến cuối năm 2025, TP.HCM đã lắp đặt 31 <a target="_blank" rel="noopener noreferrer nofollow" class="seo-suggest-link link-inline-content" href="https://thanhnien.vn/camera-ai.html">camera AI</a> tại các giao lộ và tuyến đường trọng yếu, nơi thường xuyên xảy ra vi phạm, ùn tắc và tai nạn giao thông như Điện Biên Phủ, Võ Thị Sáu, Nguyễn Thị Minh Khai, Nguyễn Hữu Cảnh, Xô Viết Nghệ Tĩnh, xa lộ Hà Nội, Nguyễn Thị Định, Đặng Thúc Vịnh…</p><p style="text-align: justify;">Thượng tá Nguyễn Văn Bình, Phó trưởng phòng CSGT (PC08) Công an TP.HCM, cho biết khác với camera giám sát thông thường, <a target="_blank" rel="noopener noreferrer nofollow" class="seo-suggest-link link-inline-content" href="https://thanhnien.vn/5-ngay-camera-ai-phat-hien-759-truong-hop-vi-pham-chu-yeu-la-vuot-den-do-185251217213212085.htm">camera AI</a> có khả năng phân tích hình ảnh theo thời gian thực, phát hiện nhiều hành vi vi phạm cùng lúc như: không chấp hành hiệu lệnh đèn tín hiệu giao thông, không chấp hành vạch kẻ đường, đi sai làn, chạy ngược chiều… Bên cạnh đó, hệ thống còn tích hợp các tính năng bổ trợ như đo đếm lưu lượng, phát hiện ùn tắc, nhận diện phương tiện trong danh sách đen.</p><p style="text-align: justify;"><img src="http://localhost:8888/api/v1/resource/download/asset/7daeb47a-8470-4e75-b2d6-2690f11d393b.webp"></p><p style="text-align: justify;">Theo thượng tá Nguyễn Văn Bình, từ khi đưa vào vận hành, hệ thống camera AI đã phát hiện 7.198 trường hợp vi phạm, trong đó các lỗi phổ biến nhất là vượt đèn đỏ, sai làn, không chấp hành vạch kẻ đường và đi ngược chiều.</p><p style="text-align: justify;">Phó trưởng PC08 cho hay, việc xử phạt vi phạm giao thông bằng camera AI được thực hiện theo quy trình khép kín, từ phát hiện đến xử lý, trên nền tảng dữ liệu số đồng bộ.</p><p style="text-align: justify;">Quy trình xử lý vi phạm bằng camera AI bắt đầu từ việc hệ thống tự động phát hiện vi phạm qua camera hoặc phản ánh của người dân trên VNeTraffic. Dữ liệu sau đó được kết nối với các cơ sở dữ liệu quốc gia để xác định phương tiện, chủ phương tiện. Cán bộ CSGT trực tiếp kiểm tra, xác minh hình ảnh trước khi gửi thông báo vi phạm và lập biên bản, ra quyết định xử phạt theo đúng quy định pháp luật.</p><p style="text-align: justify;"><img src="http://localhost:8888/api/v1/resource/download/asset/e1c47fcc-fe14-4cd6-8c2e-bef63585faf9.webp"></p><p style="text-align: justify;">Lãnh đạo PC08 đánh giá, ứng dụng camera AI không chỉ là "lắp thêm mắt" cho lực lượng CSGT, mà còn tạo ra sự chuyển đổi căn bản trong phương thức làm việc, từ mô hình thủ công dựa vào sức người sang mô hình quản lý bằng công nghệ và dữ liệu.</p><p style="text-align: justify;">"Dùng camera AI vào phát hiện vi phạm với hình ảnh rõ ràng, giảm tiếp xúc trực tiếp giữa người thực thi công vụ với người dân, bảo đảm tính khách quan, công bằng vì ai cũng bị xử lý như nhau", thượng tá Nguyễn Văn Bình nhấn mạnh.</p><p style="text-align: justify;">Theo ghi nhận, công an các địa phương đang tổng rà soát, làm sạch dữ liệu đăng ký xe, bằng lái xe nhằm xây dựng cơ sở dữ liệu bảo đảm dữ liệu "đúng, đủ, sạch, sống".</p><p style="text-align: justify;">Như vậy, sau khi dữ liệu được cập nhật cộng với hệ thống <a target="_blank" rel="noopener noreferrer nofollow" class="link-inline-content" href="https://thanhnien.vn/csgt-huong-dan-cach-di-duong-dung-luat-de-khong-bi-camera-phat-nguoi-185251222210414251.htm">camera phạt nguội</a> khắp nơi, người tham gia giao thông bắt buộc phải tuân thủ các quy định. Mọi vi phạm đều có thể bị hệ thống camera này hoặc người đi đường quay clip gửi CSGT.</p><h2 style="text-align: justify;"><strong>TRUY VẾT CON NGƯỜI, PHƯƠNG TIỆN HỖ TRỢ ĐIỀU TRA</strong></h2><p style="text-align: justify;">Hiện Trung tâm chỉ huy giao thông của Cục CSGT (C08), Bộ Công an đang sử dụng camera AI do các đơn vị thuộc Bộ Công an sản xuất, được thiết kế với nhiều nhóm tính năng phục vụ đồng thời công tác xử lý vi phạm, điều tra tai nạn và bảo đảm an ninh trật tự.</p><p style="text-align: justify;">Trong giai đoạn tiếp theo, người dân sẽ có thể xác nhận vi phạm và nộp phạt trực tuyến ngay trên ứng dụng, giảm đi lại và rút gọn thủ tục hành chính.</p><p style="text-align: justify;">Bên cạnh xử lý vi phạm, hệ thống camera AI còn hỗ trợ điều tra, thống kê tai nạn giao thông, cho phép CSGT lập biên bản ngay tại hiện trường, cập nhật dữ liệu tức thời và xác định các điểm đen tai nạn trên bản đồ để phục vụ công tác điều hành, bố trí lực lượng.</p><p style="text-align: justify;">Ngoài ra, camera AI còn có khả năng tra cứu, truy vết thông tin phương tiện và con người, phục vụ công tác bảo đảm an ninh trật tự và ATGT. Hệ thống có thể nhận diện phương tiện theo màu sắc, loại xe, biển số để truy vết lộ trình, xác định thời điểm gần nhất phương tiện vi phạm hoặc gây tai nạn.<br>Đồng thời, AI cũng hỗ trợ nhận diện đặc điểm khuôn mặt, phục vụ truy tìm đối tượng truy nã, tình nghi đối tượng để cảnh báo ngay khi xuất hiện trên hệ thống camera.</p><p style="text-align: justify;">Đáng chú ý, hệ thống còn có chức năng cảnh báo sớm các hành vi gây mất an ninh trật tự, như mang theo hung khí, tụ tập đông người bất thường, đánh nhau, gây rối… và hiển thị cảnh báo tức thời trên bản đồ giám sát để lực lượng chức năng kịp thời xử lý.</p><p style="text-align: justify;">"Không chỉ phục vụ xử phạt, hệ thống camera AI còn có khả năng dựng lại hành trình phương tiện trước và sau tai nạn, hỗ trợ điều tra, truy vết phương tiện nghi vấn, phát hiện hành vi gây mất an ninh trật tự như mang hung khí, tụ tập bất thường", đại diện Cục CSGT chia sẻ.</p><p style="text-align: justify;">Theo Đề án Quy hoạch trung tâm dữ liệu, quản lý, giám sát xử lý vi phạm và điều hành giao thông của Bộ Công an, 34 tỉnh, thành sẽ có camera AI với các tính năng giống trung tâm chỉ huy giao thông.</p><p style="text-align: justify;"><img src="http://localhost:8888/api/v1/resource/download/asset/2933a814-6b3c-439b-9d1e-83ff1fc49ccb.webp"></p><h2 style="text-align: justify;"><strong>KHÔNG PHÓ MẶC HOÀN TOÀN CHO AI</strong></h2><p style="text-align: justify;">Thượng tá Nguyễn Văn Bình đánh giá, camera AI là giải pháp hiệu quả để giải quyết bài toán giao thông tại TP.HCM. Tuy nhiên, việc triển khai camera AI sẽ áp dụng theo tính đặc thù của giao thông TP.HCM, thích ứng với đặc thù giao thông phức tạp, mật độ phương tiện cao.</p><p style="text-align: justify;">Theo đó, tại các giao lộ của TP.HCM, lưu lượng xe đông, CSGT sẽ lựa chọn công nghệ và camera AI có khả năng chụp và phân tích đồng thời nhiều phương tiện, hành vi của người tham gia giao thông. Các camera AI sẽ được huấn luyện đặc biệt để nhận diện các hành vi vi phạm của nhiều loại phương tiện, thay vì chỉ bắt 1 lỗi vi phạm.</p><p style="text-align: justify;">Lãnh đạo PC08 cho hay, TP.HCM có nhiều quy định cấm xe tải, xe khách theo giờ hoặc theo tuyến đường và trong tương lai TP.HCM sẽ triển khai "Đề án kiểm soát khí thải phương tiện giao thông". Do đó, việc dừng xe để kiểm tra giấy phép vào tuyến đường cấm có thể gây ùn tắc nên camera AI sẽ được triển khai để tự động tra soát biển số với cơ sở dữ liệu để biết xe đó có được phép đi vào giờ đó hay không.</p><p style="text-align: justify;">"Do đặc thù giao thông của TP.HCM, CSGT sẽ không thể phó mặc hoàn toàn cho máy, 100% hình ảnh vi phạm do camera AI gửi về đều phải qua cán bộ tại trung tâm lọc lại trước khi trích xuất dữ liệu xử phạt để đảm bảo tính chính xác khi ra quyết định xử phạt", thượng tá Nguyễn Văn Bình thông tin.</p>	684ef412-6f7f-43f5-a0a9-5739cf8b4013	http://localhost:8888/api/v1/resource/download/asset/cc7bcdc2-c752-41a3-9a1f-4b3b3d25ba95.webp
<p>hêh</p><img class="editor-image" src="http://localhost:8888/api/v1/resource/download/asset/40eecaaf-5d4e-4bb9-bd71-709e7275313e.png"><p></p>	4817032e-309f-4a0b-af0b-3e2da3d985da	http://localhost:8888/api/v1/resource/download/asset/75518b81-cada-45e4-a22a-bba87e5201e7.png
<h2 style="text-align: justify;"><span style="font-family: Merriweather, serif;"><strong>Sau khi có kết quả xổ số miền Nam ngày 28 tháng 12, một đại lý vé số ở Tây Ninh đổi thưởng 5 tờ vé số trúng giải cho khách.</strong></span></h2><p style="text-align: justify;"><span style="font-family: Merriweather, serif;">Đại lý vé số Tuấn ở Tây Ninh (Long An cũ) vừa đổi thưởng cho khách có 5 tờ trúng số. Cụ thể, 5 tờ có 5 số cuối là 73763 thuộc đài Tiền Giang mở thưởng </span><a target="_blank" rel="noopener noreferrer nofollow" href="https://thanhnien.vn/xo-so-mien-nam-ngay-28-thang-12-ket-qua-xo-so-hom-nay-chu-nhat-185251228140950917.htm"><span style="font-family: Merriweather, serif;">xổ số miền Nam ngày 28 tháng 12</span></a><span style="font-family: Merriweather, serif;"> trúng giải nhất trị giá 150 triệu đồng (chưa trừ thuế). Trong khi đó giải độc đắc của đài này thuộc về những tờ có dãy số 121031.</span></p><img class="editor-image" src="http://localhost:8888/api/v1/resource/download/asset/ca88ad23-0917-45c8-a9b3-68eecd974d39.webp"><p><span style="font-family: Merriweather, serif;">"Chủ nhân của 5 tờ vé số may mắn là người đàn ông. Người này mua ủng hộ người bán dạo, sau khi có kết quả </span><a target="_blank" rel="noopener noreferrer nofollow" href="https://thanhnien.vn/bat-ngo-xo-so-mien-nam-xuat-hien-day-so-trung-2-giai-2-ngay-lien-tuc-185251227065513964.htm"><span style="font-family: Merriweather, serif;">xổ số miền Nam hôm nay</span></a><span style="font-family: Merriweather, serif;"> liền đến đại lý đổi thưởng và nhận toàn bộ tiền trúng số qua hình thức chuyển khoản. Tôi kinh doanh vé số từ năm 2000 đến nay, thỉnh thoảng đổi thưởng vé số trúng độc đắc cho khách", đại lý vé số Tuấn cho hay.</span></p><p style="text-align: justify;"><span style="font-family: Merriweather, serif;">Đại lý vé số Hải Diệu ở Đồng Nai đăng tải hình ảnh sau khi đổi thưởng cho khách có 14 tờ trúng khuyến khích theo kết quả xổ số ngày 28 tháng 12. Cụ thể, 14 tờ có dãy số 126031 thuộc đài Tiền Giang trúng khuyến khích trị giá 84 triệu đồng.</span></p><p style="text-align: justify;"><span style="font-family: Merriweather, serif;">Hình ảnh những tờ vé số trúng giải sau khi đăng tải lên mạng xã hội thu hút sự quan tâm của mọi người. Ai nấy đều gửi lời chúc đến chủ nhân may mắn, không quên "xin vía" để bản thân sớm trúng số.</span></p><p style="text-align: justify;"><span style="font-family: Merriweather, serif;">Gần đây, theo kết những tờ vé có dãy số cuối may mắn 12931 xổ số miền Nam ngày 26 tháng 12 đài Trà Vinh đã trúng giải tư, trị giá 3 triệu đồng/vé. Điều thú vị là dãy số này cũng trúng giải tám của đài trên khi có số cuối là 31. Điều này khiến người chơi xổ số thích thú, truy tìm những tờ vé số có dãy trên vì cho rằng một tờ vé cùng lúc trúng 2 giải là điều may mắn.</span></p>	772f3db7-64fb-4d42-826b-d90a29013116	http://localhost:8888/api/v1/resource/download/asset/80732539-8838-4187-a780-0b636d67e039.webp
\.


--
-- Data for Name: resource; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.resource (id, created_at, owner_id, title, type, updated_at, visibility) FROM stdin;
86b83329-ac18-426f-907d-25491aac2d6f	2025-12-17 13:45:23.418095		CV_LeVoDangKhoa.pdf	DOCUMENT	2025-12-17 13:45:23.418139	PUBLIC
a0a36ef5-aac7-4ec9-8ae1-d31bed2e5c81	2025-12-17 14:12:09.162899		Đề CK 211.pdf	DOCUMENT	2025-12-17 14:12:09.162937	PUBLIC
da895b67-9fb3-4ca3-8235-6396cb775c2a	2025-12-17 14:21:54.336578		Đề CK 211.pdf	DOCUMENT	2025-12-17 14:21:54.336619	PUBLIC
acfab06b-a474-473f-b25a-a7742fde5a45	2025-12-17 14:27:10.256562		Đề CK 211.pdf	DOCUMENT	2025-12-17 14:27:10.256606	PUBLIC
09d3734c-5847-451b-8475-1f885a144236	2025-12-17 14:51:01.688609		CV_LeVoDangKhoa (1).pdf	DOCUMENT	2025-12-17 14:51:01.688649	PUBLIC
44238dd8-94e8-4644-8790-a2ed37e70703	2025-12-25 16:06:46.639348		Ứng dụng của vải ko dệt trong Sx lọc nước:khí-Nhóm 1	DOCUMENT	2025-12-29 14:12:08.564715	PUBLIC
391c7875-f335-40d6-b4b4-4275c096e1d2	2025-12-27 09:49:20.485255	5c240a33-aa0c-4d98-bd88-68c52dc86486	Nghi vấn 'bắt tay' từng khiến U.23 Việt Nam bị loại đau đớn khỏi U.23 châu Á	POST	2025-12-27 09:49:20.485262	PUBLIC
fad67e09-0bf8-44cb-bf77-d75a4e6c7df4	2025-12-27 10:39:26.113577	5c240a33-aa0c-4d98-bd88-68c52dc86486	U.23 Việt Nam vô địch vòng bảng U.23 châu Á	POST	2025-12-27 10:39:26.113589	PUBLIC
9f30a3ce-a937-42ca-a3e5-faff19931f09	2025-12-25 15:11:51.692321		architecture	DOCUMENT	2025-12-29 14:12:19.481047	PUBLIC
e560b01a-50d5-468b-b161-42016d0a16c2	2025-12-25 13:22:50.763966		HEHHEE	DOCUMENT	2025-12-29 14:08:21.319391	PRIVATE
97d43ee0-f6b5-4210-bbb9-5a69eb273295	2025-12-27 14:31:41.648225	5c240a33-aa0c-4d98-bd88-68c52dc86486	U.23 Việt Nam vô địch vòng bảng U.23 châu Á	POST	2025-12-27 14:31:41.648239	PUBLIC
ab3ef374-dcda-4299-9f5e-68f5702a8cf7	2025-12-27 14:34:10.328312	5c240a33-aa0c-4d98-bd88-68c52dc86486	U.23 Việt Nam vô địch vòng bảng U.23 châu Á	POST	2025-12-27 14:34:10.328327	PUBLIC
2154aca8-3692-451c-a9ef-318fd9d0ec17	2025-12-27 15:00:05.842152	5c240a33-aa0c-4d98-bd88-68c52dc86486	ok	POST	2025-12-27 15:00:05.84216	PUBLIC
b4eb7322-e7a8-46aa-bcff-307896a665c0	2025-12-27 15:04:02.582741	5c240a33-aa0c-4d98-bd88-68c52dc86486	ok	POST	2025-12-27 15:04:02.582745	PUBLIC
f4891a29-007e-4242-b26e-76dcf2a3294c	2025-12-27 15:06:52.710671	5c240a33-aa0c-4d98-bd88-68c52dc86486	ahdjaehdjaed	POST	2025-12-27 15:06:52.710675	PUBLIC
42fba902-d39c-4817-85b6-5b5bfb2f67c1	2025-12-25 10:03:34.499073		10 Listening - Test 1	DOCUMENT	2025-12-29 14:08:37.27846	PUBLIC
094b687d-f40c-40d5-bb88-d569f89d64ae	2025-12-25 13:31:27.3321		932db37e-7cb1-4db6-bb88-0e9c248e77db_answer	DOCUMENT	2025-12-29 14:08:27.383435	PUBLIC
a6a32582-f025-4091-9675-6ad8f774dbf6	2025-12-25 15:11:51.4891		932db37e-7cb1-4db6-bb88-0e9c248e77db_answer	DOCUMENT	2025-12-29 14:12:19.949312	PUBLIC
a2bf5e9b-1813-4b6b-b060-75312924b37b	2025-12-25 13:35:23.792573		dethi_LTW_HK2_2020_2021	DOCUMENT	2025-12-29 14:08:37.73682	PUBLIC
e58907a3-e4f3-486f-ade8-4901f7d2d3c4	2025-12-25 13:39:39.391929		10 Listening - Test 1	DOCUMENT	2025-12-29 14:12:20.325171	PUBLIC
6d98052c-4f94-48b7-929f-f75a52750be1	2025-12-25 13:33:43.46072		10 Listening - Test 1	DOCUMENT	2025-12-29 14:08:40.37828	PUBLIC
918a6ca4-b957-48eb-8b62-189b873c315b	2025-12-29 14:11:57.986994	default-owner-id	Báo cáo đồ án	DOCUMENT	2025-12-29 14:12:32.540339	PUBLIC
8cfbf39f-07b2-4eed-9464-62ab33054749	2025-12-28 08:11:03.212298	5c240a33-aa0c-4d98-bd88-68c52dc86486	OKOKKKKK	POST	2025-12-28 08:11:03.212311	PUBLIC
684ef412-6f7f-43f5-a0a9-5739cf8b4013	2025-12-28 08:32:52.353556	5c240a33-aa0c-4d98-bd88-68c52dc86486	Camera AI dựa vào cơ sở nào để xử phạt?	POST	2025-12-28 08:32:52.35357	PUBLIC
4817032e-309f-4a0b-af0b-3e2da3d985da	2025-12-29 14:00:40.323134	5c240a33-aa0c-4d98-bd88-68c52dc86486	abcdefgh	POST	2025-12-29 14:00:40.323141	PUBLIC
772f3db7-64fb-4d42-826b-d90a29013116	2025-12-29 14:03:04.142689	5c240a33-aa0c-4d98-bd88-68c52dc86486	Xổ số miền Nam ngày 28 tháng 12: Lộ diện 19 tờ trúng số đài Tiền Giang	POST	2025-12-29 14:03:04.142708	PUBLIC
5f0d2f31-238e-4f05-9b56-257643db9a40	2025-12-26 10:50:19.250019		932db37e-7cb1-4db6-bb88-0e9c248e77db_answer	DOCUMENT	2025-12-26 10:50:19.250586	PUBLIC
02ef68d6-fa93-4ffa-9ad5-53ef3d11b804	2025-12-25 13:37:45.117957		web251	DOCUMENT	2025-12-29 14:12:02.152683	PUBLIC
46121fd6-3130-4989-8c7c-934b7313963c	2025-12-27 15:13:00.394503	default-owner-id	bu2	DOCUMENT	2025-12-29 14:12:04.566262	PUBLIC
de7efa45-be6a-423f-a08f-201433010899	2025-12-29 14:06:47.384349	default-owner-id	dacn_class_diagram	DOCUMENT	2025-12-29 14:12:04.572214	PUBLIC
7bdfea25-7af5-4546-8cef-1747f8f6c30c	2025-12-26 15:39:54.652316		Bản sao HK241_56_DATN_LVTN_Finish_NguyenLeXuanHoa_2033145_4	DOCUMENT	2025-12-29 14:12:05.244454	PUBLIC
20f6eb69-7e3b-451a-8f46-9d6f0bcd241b	2025-12-26 15:35:40.814014		dacn_class_diagram	DOCUMENT	2025-12-29 14:12:07.120903	PUBLIC
a0a9b085-6641-4fc4-84cc-229648876353	2025-12-25 13:25:07.720316		2ok	DOCUMENT	2025-12-29 14:08:36.261293	PUBLIC
\.


--
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.subject (id, name) FROM stdin;
INT1001	Nhập môn Công nghệ thông tin
INT1002	Kỹ thuật Lập trình C/C++
INT1003	Lập trình Hướng đối tượng (Java)
INT1004	Cấu trúc dữ liệu và Giải thuật
INT1005	Cơ sở dữ liệu
INT1006	Mạng máy tính
INT1007	Hệ điều hành
INT1008	Kiến trúc máy tính
INT1009	Phân tích và thiết kế hệ thống
SE1010	Công nghệ phần mềm
WEB1011	Lập trình Web Frontend
WEB1012	Lập trình Web Backend
MOB1013	Lập trình thiết bị di động (Android/iOS)
AI1014	Trí tuệ nhân tạo
SEC1015	An toàn và bảo mật thông tin
DATA1016	Khoa học dữ liệu
IOT1017	Internet vạn vật (IoT)
CLD1018	Điện toán đám mây
MAT2001	Giải tích 1
MAT2002	Giải tích 2
MAT2003	Đại số tuyến tính
MAT2004	Toán rời rạc
MAT2005	Xác suất thống kê
GEN3001	Triết học Mác - Lênin
GEN3002	Kinh tế chính trị
GEN3003	Tư tưởng Hồ Chí Minh
GEN3004	Lịch sử Đảng
PHY3005	Vật lý đại cương
ENG4001	Tiếng Anh cơ bản 1
ENG4002	Tiếng Anh cơ bản 2
ENG4003	Tiếng Anh chuyên ngành
JPN4004	Tiếng Nhật sơ cấp
SKL5001	Kỹ năng giao tiếp và làm việc nhóm
SKL5002	Tư duy phản biện
SKL5003	Kỹ năng viết báo cáo kỹ thuật
\.


--
-- Data for Name: topic; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.topic (id, name, subject_id) FROM stdin;
8b64cf76-d24d-4055-96ec-468a2790f834	Lịch sử phát triển máy tính	INT1001
4d5503d9-e24f-4945-a5dc-1c65d66a33be	Biểu diễn thông tin trong máy tính	INT1001
b04e6971-0ad8-4f5d-a07f-d9beb82f11ae	Con trỏ và quản lý bộ nhớ	INT1002
da48d282-1d64-477c-954d-eeaf1fdd50a0	Đệ quy và Hàm	INT1002
71fef4b1-46f5-4e2f-9f63-2019f0932799	Lớp và Đối tượng (Class & Object)	INT1003
c7fd7656-df18-446b-9018-b257d09d60d5	Tính kế thừa và Đa hình	INT1003
c888d93c-5724-4133-8d46-365279bdf239	Xử lý ngoại lệ (Exception Handling)	INT1003
98e74a34-6419-4463-9bad-ba6e03213996	Các thuật toán sắp xếp (Sorting)	INT1004
aa6e10ca-8774-4ec3-bddb-9a020d86133b	Danh sách liên kết (Linked List)	INT1004
9f36e1de-a9ad-4c34-8b4d-0b48dea10f89	Cây nhị phân và Đồ thị	INT1004
3c46a94f-d8ae-4606-a380-9574b7cec880	Mô hình thực thể kết hợp (ERD)	INT1005
2e7c6837-15ec-4864-bbf4-447c242acf8d	Ngôn ngữ truy vấn SQL	INT1005
a30de17e-d653-4094-818b-cdf438c07565	Chuẩn hóa dữ liệu	INT1005
34a107fa-9176-44d9-b796-3091f1f64d5b	Mô hình OSI và TCP/IP	INT1006
dea2bb93-ead2-4f4d-894a-e14da601e40b	Định tuyến và chuyển mạch	INT1006
5a2518c9-2932-4b56-a8f0-b1727b403b3f	Quản lý tiến trình (Process Management)	INT1007
68f6ffb0-8fa1-4e14-a00c-85c1c67a8054	Quản lý bộ nhớ và Hệ thống tập tin	INT1007
081a6abd-3014-4287-bec1-7a63bfd1866e	Deadlock và cách xử lý	INT1007
8c11efea-cd47-4968-a98c-e28cdef93a4d	Quy trình phát triển phần mềm (SDLC)	SE1010
bb0981cc-8787-470c-b5f1-8a9f222cdcda	Mô hình Agile và Scrum	SE1010
615e8a19-4a45-4b3b-ad06-fd8da271a777	Kiểm thử phần mềm (Testing)	SE1010
f4c9bf11-fa87-45c4-9281-82b456789516	HTML5 và ngữ nghĩa	WEB1011
0a523c71-9568-4f4e-9e8d-54d809b0c0c2	CSS3 và Responsive Design	WEB1011
2a414da5-fc4a-4916-a79a-5449c403b9f6	JavaScript ES6+ và DOM	WEB1011
fbfe3969-8f91-46e8-a954-b43b3c31c082	Kiến trúc RESTful API	WEB1012
0de769a1-a6c5-4857-87ad-4861d91239a4	Kết nối cơ sở dữ liệu với ORM	WEB1012
85a1b0b5-0443-4f3e-a542-e1eb9a620b21	Vòng đời ứng dụng (Activity Lifecycle)	MOB1013
67539a30-f82e-47ef-b2ab-b1bdfa8cd451	Thiết kế giao diện Mobile	MOB1013
af00e66c-d0e8-404c-8e18-699c72d11aa1	Các thuật toán tìm kiếm (Search Algorithms)	AI1014
cc929469-37f0-4f03-ba1f-3c375baf80d2	Mạng nơ-ron nhân tạo	AI1014
4602a955-5262-4a29-a1e1-e0bddcbe9988	Học máy (Machine Learning) cơ bản	AI1014
fb9098e1-58f8-4ae3-81a3-65c6895c067e	Mã hóa đối xứng và bất đối xứng	SEC1015
06cde5de-1174-41ec-92b7-959737268137	Các lỗ hổng web phổ biến (OWASP)	SEC1015
92ddc249-0206-4e8c-a45a-1ec67a424edd	Tiền xử lý dữ liệu (Data Preprocessing)	DATA1016
4d0f9c67-f435-445c-8e14-d17e304d387f	Trực quan hóa dữ liệu	DATA1016
9b2550cc-63c1-4e2b-8fcc-0a2b959bc624	Giới hạn và tính liên tục	MAT2001
ed85b7b6-326b-43f9-a29c-ec3cdbbdfd81	Đạo hàm và vi phân	MAT2001
8123537d-68e4-4b37-9236-87a62d28557e	Ma trận và Định thức	MAT2003
dfa90232-4669-46aa-808c-bdba061b2e77	Không gian vector	MAT2003
e18b7409-66d5-4e3c-b236-57dc6d5848f0	Lý thuyết tập hợp và Logic	MAT2004
9985e8d3-080b-4500-92bf-0f16cdb88397	Lý thuyết đồ thị	MAT2004
6ca5dc36-2fde-48e3-acb4-20cd22ec0a1c	Biến ngẫu nhiên và hàm phân phối	MAT2005
954d36cf-86ef-4ce7-8f78-599cbdcceff6	Kiểm định giả thuyết	MAT2005
b7540a91-7b5d-4e8a-aae3-5378319c9a35	Chủ nghĩa duy vật biện chứng	GEN3001
b5777157-87b5-4d5c-a4e7-cfd0bcb2791a	Quy luật mâu thuẫn	GEN3001
2bd9d1cf-2e7a-4a34-a383-64c2fb396f5a	Hàng hóa và tiền tệ	GEN3002
918947aa-a3c6-4e69-a354-415bff1be9b1	Giá trị thặng dư	GEN3002
f309dc56-9138-420c-8fc3-14b7d209a4e8	Thì hiện tại đơn và tiếp diễn	ENG4001
25e87704-329f-4a8a-a182-fce2352b594e	Từ vựng về gia đình và công việc	ENG4001
cd1a09ba-c5c9-4ade-a050-5c9bb664628f	Đọc hiểu tài liệu kỹ thuật	ENG4003
93bdd519-f477-47cc-9686-0cefdfe7397f	Viết Email công việc	ENG4003
ac9d3f71-fb59-4bc1-875b-915ecd4b0cf4	Kỹ năng lắng nghe tích cực	SKL5001
a55171c2-7b9c-4585-98b6-f58cc29d22c6	Giải quyết xung đột nhóm	SKL5001
67a0e177-a4c6-45b0-870f-48e729433f1e	Phân tích lập luận	SKL5002
322ac012-dad5-40c2-a28c-84d2eb328467	Các loại ngụy biện thường gặp	SKL5002
\.


--
-- Data for Name: tutor; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.tutor (id, average_rating, introduction, rating_count, status, avatar, name) FROM stdin;
95da25ef-99da-4a8f-86a2-2ec0d400f307	0	Giảng viên chuyên khoa HTTT	0	ACTIVE	url to the image	Gia sư Minh
\.


--
-- Data for Name: tutor_subjects; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.tutor_subjects (tutor_id, subject_id) FROM stdin;
95da25ef-99da-4a8f-86a2-2ec0d400f307	INT1005
95da25ef-99da-4a8f-86a2-2ec0d400f307	AI1014
\.


--
-- Data for Name: universities; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.universities (id, abbreviation, logo_url, name) FROM stdin;
1	HCMUT	\N	Trường Đại học Bách Khoa - ĐHQG TP.HCM
2	HCMUS	\N	Trường Đại học Khoa học Tự nhiên - ĐHQG TP.HCM
3	UIT	\N	Trường Đại học Công nghệ Thông tin - ĐHQG TP.HCM
4	USSH	\N	Trường Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM
5	IU	\N	Trường Đại học Quốc tế - ĐHQG TP.HCM
6	UEL	\N	Trường Đại học Kinh tế - Luật - ĐHQG TP.HCM
7	HCMUTE	\N	Trường Đại học Sư phạm Kỹ thuật TP.HCM
8	UEH	\N	Trường Đại học Kinh tế TP.HCM
9	NLU	\N	Trường Đại học Nông Lâm TP.HCM
10	UMP	\N	Trường Đại học Y Dược TP.HCM
11	SGU	\N	Trường Đại học Sài Gòn
12	OU	\N	Trường Đại học Mở TP.HCM
13	ULAW	\N	Trường Đại học Luật TP.HCM
14	IUH	\N	Trường Đại học Công nghiệp TP.HCM
15	TDTU	\N	Trường Đại học Tôn Đức Thắng
16	UFM	\N	Trường Đại học Tài chính - Marketing
17	UTH	\N	Trường Đại học Giao thông Vận tải TP.HCM
18	HUB	\N	Trường Đại học Ngân hàng TP.HCM
19	UARCH	\N	Trường Đại học Kiến trúc TP.HCM
20	RMIT	\N	Đại học RMIT Việt Nam
21	FPT	\N	Trường Đại học FPT
22	HUTECH	\N	Trường Đại học Công nghệ TP.HCM
23	VLU	\N	Trường Đại học Văn Lang
24	HSU	\N	Trường Đại học Hoa Sen
25	HUST	\N	Trường Đại học Bách Khoa Hà Nội
26	NEU	\N	Trường Đại học Kinh tế Quốc dân
27	VNU	\N	Trường Đại học Quốc gia Hà Nội
28	FTU	\N	Trường Đại học Ngoại thương
29	DUT	\N	Trường Đại học Bách Khoa - ĐH Đà Nẵng
30	UED	\N	Trường Đại học Sư phạm - ĐH Đà Nẵng
\.


--
-- Data for Name: user_profiles; Type: TABLE DATA; Schema: public; Owner: bkument
--

COPY public.user_profiles (id, account_id, address, avatar_url, bio, dob, email, first_name, last_name, phone, points, university_id) FROM stdin;
95da25ef-99da-4a8f-86a2-2ec0d400f307	fd87318b-a289-4b85-91fd-e8ce29c708fd	Quận 1, TP.HCM	url to the image	CSE	2026-12-06	minh.nguyen@example.com	Minh	Nguyễn Văn	0901234567	0	1
5d789001-45ee-4b53-a269-14ec290af319	40f6faa4-20c3-40de-ae60-2a406b494d3b	string	\N	string	2000-02-07	ly.quang	Ly	Quang	123456	0	1
702c6242-61fa-4d0d-af0a-855cdbb30b67	11b74b8f-2be2-4060-b537-d7af7314736a	string	\N	string	2000-02-07	ly.quang@gmail.com	Ly	Quang	123456	0	1
c548946c-e254-4dd7-8eb3-15f1b097f1d5	5f3eef47-e6b2-4ea8-a814-482022a9be87	string	\N	string	2000-02-07	ly.quang@gmail.com	Ly	Quang	123456	0	1
664fc600-82f6-4739-bc82-291679436803	305a93ba-7b53-4310-9031-e5d3735093fc	tanda	\N	okee	2000-02-07	lyquangmnpq@gmail.com	Ly	Quang	123456	0	1
7f5074db-d29c-4790-9464-e2a3b188aed5	daf40f5d-6019-457b-8a1d-f56e261f02a4	tanda	\N	okee	2000-02-07	lyquangmnpq@gmail.com	Ly	Quang	123456	0	1
477d787d-2c55-4383-b79b-8f3347ede4e8	0371f5a5-2b7c-4d0d-9c2e-64b999b8274b	tanda	\N	okee	2000-02-07	lyquang123@gmail.com	Ly	Quang	123456	0	1
\.


--
-- Name: class_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bkument
--

SELECT pg_catalog.setval('public.class_schedules_id_seq', 19, true);


--
-- Name: universities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bkument
--

SELECT pg_catalog.setval('public.universities_id_seq', 30, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: blog_asset blog_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.blog_asset
    ADD CONSTRAINT blog_asset_pkey PRIMARY KEY (id);


--
-- Name: class_room class_room_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.class_room
    ADD CONSTRAINT class_room_pkey PRIMARY KEY (id);


--
-- Name: class_schedules class_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.class_schedules
    ADD CONSTRAINT class_schedules_pkey PRIMARY KEY (id);


--
-- Name: document document_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);


--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);


--
-- Name: invalidated_token invalidated_token_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.invalidated_token
    ADD CONSTRAINT invalidated_token_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: resource resource_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.resource
    ADD CONSTRAINT resource_pkey PRIMARY KEY (id);


--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);


--
-- Name: tutor tutor_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.tutor
    ADD CONSTRAINT tutor_pkey PRIMARY KEY (id);


--
-- Name: universities ukb5hrh2ogsxka1cp118awltx1i; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT ukb5hrh2ogsxka1cp118awltx1i UNIQUE (name);


--
-- Name: enrollments ukch8jko79fc9kxk951i4viayfa; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT ukch8jko79fc9kxk951i4viayfa UNIQUE (user_id, class_id);


--
-- Name: user_profiles ukopddmxm4ps5aqyvraslrkb1u1; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT ukopddmxm4ps5aqyvraslrkb1u1 UNIQUE (account_id);


--
-- Name: universities ukpdlpyi5yh3vkuppu2k7oi6jjb; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT ukpdlpyi5yh3vkuppu2k7oi6jjb UNIQUE (abbreviation);


--
-- Name: universities universities_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: class_room fk12yia2dh018gx1g1g1qbjquvn; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.class_room
    ADD CONSTRAINT fk12yia2dh018gx1g1g1qbjquvn FOREIGN KEY (tutor_id) REFERENCES public.tutor(id);


--
-- Name: enrollments fk6x5m4k75aoftvly1u72buhofb; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk6x5m4k75aoftvly1u72buhofb FOREIGN KEY (class_id) REFERENCES public.class_room(id);


--
-- Name: post fk7j2hhj9idpjsemi9kbch2rhmk; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk7j2hhj9idpjsemi9kbch2rhmk FOREIGN KEY (id) REFERENCES public.resource(id);


--
-- Name: topic fka36s3q1p2kfgtp51ydh0tx4cc; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT fka36s3q1p2kfgtp51ydh0tx4cc FOREIGN KEY (subject_id) REFERENCES public.subject(id);


--
-- Name: class_room fkan6a1ndyp4xabnl6qc4723574; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.class_room
    ADD CONSTRAINT fkan6a1ndyp4xabnl6qc4723574 FOREIGN KEY (topic_id) REFERENCES public.topic(id);


--
-- Name: document fkh1fhcxni7rne358ywm35931by; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT fkh1fhcxni7rne358ywm35931by FOREIGN KEY (id) REFERENCES public.resource(id);


--
-- Name: tutor_subjects fkrbwej4ik99xyo11357qqwucco; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.tutor_subjects
    ADD CONSTRAINT fkrbwej4ik99xyo11357qqwucco FOREIGN KEY (tutor_id) REFERENCES public.tutor(id);


--
-- Name: class_schedules fks75mol32st4adl99fwhtq5ddp; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.class_schedules
    ADD CONSTRAINT fks75mol32st4adl99fwhtq5ddp FOREIGN KEY (class_id) REFERENCES public.class_room(id);


--
-- Name: account_roles fktp61eta5i06bug3w1qr6286uf; Type: FK CONSTRAINT; Schema: public; Owner: bkument
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fktp61eta5i06bug3w1qr6286uf FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: bkument
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict 5KPthB6owcTV4r4BNBTfs2D3IUg0PYI5S9h38xqpEj1TrYqj4kAckhrzkP9Tc4P

