spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/bkument_db
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          ai-service:
            connect-timeout: 60000
            read-timeout: 1200000
  neo4j:
    uri: bolt://${DB_HOST:localhost}:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

minio:
  endpoint: http://${MINIO_HOST}:9000
  external-endpoint: ${MINIO_EXTERNAL_URL:http://${MINIO_HOST}:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  secure: false

gateway:
  base-url: ${BACKEND_HOST}
  api-prefix: /api/v1

swagger:
  gateway-url: ${BACKEND_HOST}/api/v1/document

app:
  services:
    ai: http://ai-service:8087/ai
    profile: http://profile-service:8081/profile
    social: http://social-service:8089/social
    lms: http://lms-service:8082/lms
  internal-api:
    secret: ${INTERNAL_API_SECRET}
  ranking:
    weight-download: 0.3
  hybrid:
    threshold-words: 10
    weight-semantic-short: 0.2
    weight-cf-short: 0.8
    weight-semantic-long: 0.7
    weight-cf-long: 0.3
  recommendation:
    weights:
      alpha1: 0.3 # Graph CF
      alpha2: 0.3 # Semantic
      alpha3: 0.2 # Active Class
      alpha4: 0.1 # Favorite Topic
      alpha5: 0.1 # Trending
      alpha6: 0.1 # University