server:
  port: 8086
  servlet:
    context-path: /document

spring:
  datasource:
    url: jdbc:postgresql://206.189.92.152:5432/bkument_db
    driverClassName: org.postgresql.Driver
    username: bkument
    password: bkument_thesis_252
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          ai-service:
            connect-timeout: 60000
            read-timeout: 1200000
  neo4j:
    uri: bolt://206.189.92.152:7687
    authentication:
      username: neo4j
      password: BKUMENT_THESIS_252

logging:
  level:
    org.hibernate.orm.connections.pooling: DEBUG
    com.zaxxer.hikari: DEBUG

# MinIO Configuration
minio:
  endpoint: http://206.189.92.152:9000
  access-key: bkument
  secret-key: bkument_admin
  bucket-name: documents
  secure: false

# Gateway Configuration
gateway:
  base-url: http://localhost:8888
  api-prefix: /api/v1

# Swagger Configuration
swagger:
  host-url: http://localhost:8086/document

app:
  services:
    ai: http://localhost:8087/ai
    profile: http://localhost:8081/profile