server:
  port: 8088
  servlet:
    context-path: /lms

spring:
  datasource:
    url: "jdbc:postgresql://206.189.92.152:5432/bkument_db"
    driverClassName: "org.postgresql.Driver"
    username: bkument
    password: bkument_thesis_252
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  neo4j:
    uri: bolt://206.189.92.152:7687
    authentication:
      username: neo4j
      password: BKUMENT_THESIS_252

swagger:
  host-url: http://localhost:8088/lms

jwt:
  signerKey: "5016f0096d30f88524edc817d00b36406e26788c87ea9c97d57c4b7758b5f033"

app:
  services:
    profile: http://localhost:8081/profile
    identity: http://localhost:8080/identity