server:
  port: 8090
  servlet:
    context-path: /resource

# MinIO Configuration
minio:
  endpoint: http://${MINIO_HOST}:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  secure: false

# Swagger Configuration
swagger:
<<<<<<< Updated upstream
  gateway-url: ${BACKEND_HOST}/resource
  host-url: ${BACKEND_HOST}/resource
=======
  gateway-url: ${BACKEND_HOST}/api/v1/resource
  host-url: http://localhost:8090/resource
>>>>>>> Stashed changes
