minio:
  endpoint: http://${MINIO_HOST}:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  secure: false

swagger:
  gateway-url: ${BACKEND_HOST}/api/v1/resource
