server:
  port: 8082
  servlet:
    context-path: /resource

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: bkument-files
  secure: false

# Swagger Configuration
swagger:
  host-url: http://localhost:8082/resource
