server:
  port: 8084
  servlet:
    context-path: /email

spring:
  application:
    name: email-service
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST:127.0.0.1}:27017/communication?authSource=admin
#      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.header: false

notification:
  email:
    brevo-url: ${BREVO_URL:https://api.brevo.com}
    brevo-apikey: ${BREVO_API_KEY}

swagger:
  host-url: http://localhost:8084/email
  gateway-url: ${BACKEND_HOST}/api/v1/email

app:
  internal-api:
    secret: ${INTERNAL_API_SECRET}

#logging:
#  level:
#    vn.edu.hcmut.notification.repository.httpclient.EmailClient: DEBUG
