spring:
  kafka:
    bootstrap-servers: kafka:9092

#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_HOST}:27017/communication?authSource=admin

swagger:
  gateway-url: ${BACKEND_HOST}/api/v1/email

app:
  internal-api:
    secret: ${INTERNAL_API_SECRET}
